create table if not exists employees (
    id BIGINT primary key,
    first_name VARCHAR,
    last_name VARCHAR,
    status VARCHAR(10),
    state VARCHAR(27),
    registered_on DATE,
    constraint UQ_EMPLOYEE_ID unique (id)
);

create table if not exists customers (
    id BIGINT primary key,
    status VARCHAR(11),
    state VARCHAR(12),
    registered_on DATE,
    first_warn DATE,
    second_warn DATE,
    banned_on DATE,
    constraint UQ_CUSTOMER_ID unique (id)
);

create table if not exists orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(250),
    client_id BIGINT REFERENCES customers (id) ON delete CASCADE,
    driver_id BIGINT REFERENCES employees (id) ON delete CASCADE,
    order_date DATE,
    price INTEGER,
    status VARCHAR(9)
);

create table if not exists cars (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT REFERENCES employees (id) ON delete CASCADE,
    license_plate VARCHAR(9),
    car_name VARCHAR(64),
    CONSTRAINT UQ_LICENSE_PLATE UNIQUE (license_plate)
);

create table if not exists feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_text VARCHAR(1500),
    client_id BIGINT REFERENCES customers (id) ON delete CASCADE,
    published_on DATE
);

create table if not exists losts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lost_text VARCHAR(1500),
    client_id BIGINT REFERENCES customers (id) ON delete CASCADE,
    published_on DATE
);

create table if not exists contacts (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 phone_number VARCHAR(17),
 CONSTRAINT UQ_PHONE_NUMBER UNIQUE (phone_number)
);

CREATE INDEX IF NOT EXISTS license_plate_index ON cars(license_plate);
