package ru.rozhdestveno.taxi.entity.employee;

public enum EmployeeState {
    EMPLOYEE_ON_DUTY,
    EMPLOYEE_ON_WEEKEND,
    ADMIN_ADD_DELETE_ADMIN,
    ADMIN_ADD_DELETE_DISPATCHER,
    ADMIN_ADD_DELETE_DRIVER,
    ADMIN_ADD_DELETE_VEHICLE,
    ADMIN_ADD_DELETE_CONTACT,
    ADMIN_GET_CASH,
    DISPATCHER_SET_PRICE,
    DRIVER_BOARDING,
    DRIVER_ACCEPT_ORDER,
    DRIVER_CLOSE_TO_CLIENT,
    DRIVER_DRIVER_ARRIVED,
    DRIVER_ON_PAUSE,
    DRIVER_SEND_MESSAGE,
    BAN_CUSTOMER,
    LOST_MONTH_REPORT,
    LOST_YEAR_REPORT,
    FEEDBACK_MONTH_REPORT,
    FEEDBACK_YEAR_REPORT
}
